/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_button_state                   16
#define gattdb_HRSPO2_Monitor                 18
#define gattdb_Heart_Rate_Spo2                20
#define gattdb_hrspo2_cccd                    22
#define gattdb_Fall_Detection_Service         23
#define gattdb_Fall_characteristic            25
#define gattdb_fall_cccd                      27


#endif // __GATT_DB_H
