/*
 * ble.h
 *
 *  Created on: Feb 15, 2026
 *      Author: Nalin Saxena
 *
 * File Brief- Header file for All BLE related Apis, and helper macros
 */

#ifndef SRC_BLE_H_
#define SRC_BLE_H_
#include "app_assert.h"
#include "sl_bt_api.h"
#include "gatt_db.h"
#include "ble_device_type.h"
#include"lcd.h"

// taken from lecture slides
#define UINT8_TO_BITSTREAM(p, n) \
    {                            \
        *(p)++ = (uint8_t)(n);   \
    }

// taken from lecture slides
#define UINT32_TO_BITSTREAM(p, n)      \
    {                                  \
        *(p)++ = (uint8_t)(n);         \
        *(p)++ = (uint8_t)((n) >> 8);  \
        *(p)++ = (uint8_t)((n) >> 16); \
        *(p)++ = (uint8_t)((n) >> 24); \
    }
#define INT32_TO_FLOAT(m, e) ((int32_t)(((uint32_t)m) & 0x00FFFFFFU) | (((uint32_t)e) << 24))



// BLE Data Structure, save all of our private BT data in here.
// Modern C (circa 2021 does it this way)
// typedef ble_data_struct_t is referred to as an anonymous struct definition
typedef struct
{
    // values that are common to servers and clients
    bd_addr myAddress;

    // values unique for server
    // The advertising set handle allocated from Bluetooth stack.
    uint8_t advertisingSetHandle;
    uint32_t  serviceHandle;
    uint16_t characteristicHandle;
    uint8_t connectionHandle;
    bool htmIndicationsEnabled;  // a bool flag for indications enabled
    bool is_Indication_Inflight; // a bool flag for indications in flight
    bool connectionOpen;         // a bool flag to indicate of we have an active connection open

    // values unique for client
} ble_data_struct_t;

/*
this is not a state machine function but an event responder function
handle_ble_event responds to events generated by the silicon labs ble state machine
*/
void handle_ble_event(sl_bt_msg_t *evt);

// a getter function for ble data ptr
ble_data_struct_t *getBleDataPtr();

#endif /* SRC_BLE_H_ */
