/*
 * ble.h
 *
 *  Created on: Feb 15, 2026
 *      Author: Nalin Saxena
 *
 * File Brief- Header file for All BLE related Apis, and helper macros
 */

#ifndef SRC_BLE_H_
#define SRC_BLE_H_
#include "app_assert.h"
#include "sl_bt_api.h"
#include "sl_sleeptimer.h"
#include "gatt_db.h"
#include "ble_device_type.h"
#include"lcd.h"


// BLE Data Structure, save all of our private BT data in here.
// Modern C (circa 2021 does it this way)
// typedef ble_data_struct_t is referred to as an anonymous struct definition
typedef struct
{
    // values that are common to servers and clients
    bd_addr myAddress;

    // values unique for server
    // The advertising set handle allocated from Bluetooth stack.
    uint8_t advertisingSetHandle;
    uint32_t  serviceHandle_hrspo2;
    uint16_t characteristicHandle_hrspo2;
    uint8_t connectionHandle;

    uint32_t serviceHandle_fall;
    uint16_t characteristicHandle_fall;
    bool fall_alert_active;

    bool HRSO2IndicationsEnabled;  // a bool flag for htm indications enabled
    bool is_Indication_Inflight; // a bool flag for indications in flight
    bool connectionOpen;         // a bool flag to indicate of we have an active connection open
    bool waitingForConfirmation; //are we waiting for btn press?
    bool bonded;  //a flag to maintain bonded status
    bool isReadRequestInflight; //have we already requested a read ?
    bool isPB0Held; //if pb0 is held and we press and release pb
    bool wasPB1Pressed; //track if PB1was pressed

    bool FallDetection_Indications_Enabled;

    // values unique for client
} ble_data_struct_t;

/*
this is not a state machine function but an event responder function
handle_ble_event responds to events generated by the silicon labs ble state machine
*/
void handle_ble_event(sl_bt_msg_t *evt);

// a getter function for ble data ptr
ble_data_struct_t *getBleDataPtr();

#endif /* SRC_BLE_H_ */
